### ISSUE TITLE
Error with latest version

### ISSUE THREAD

**Issue by fabsau** [sabrsorensen/alpine-cloudplow#18]
Hi there,

as it seems with the latest build (amd64) the startup of the application fails.
I receive the error:
`/bin/sh: /init: not found`

Using the older docker image (ghcr.io/sabrsorensen/alpine-cloudplow:04c0ca8) resolved the issue for me.

Kind Regards

**Comment by sabrsorensen** [comment]
@fabsau do the latest images resolve the error?

**Comment by fabsau** [comment]
@sabrsorensen sorry for the delay. I just switched and it seems to be resolved.
Thank you very very much!
