### ISSUE TITLE
Container not starting due to Errors

### ISSUE THREAD

**Issue by slyre1337** [sabrsorensen/alpine-cloudplow#4]
Container isn't starting anymore after an update the past couple days.

I assume one of the images it depends on did an update that broke the docker?

This is the log: (running on unraid using the "latest" tag)

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-init_user_and_fix_permissions: executing...
Permissions on /config and /opt/cloudplow restored successfully.
[cont-init.d] 10-init_user_and_fix_permissions: exited 0.
[cont-init.d] 20-cleanup_stale_locks: executing...
[cont-init.d] 20-cleanup_stale_locks: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
File "/opt/cloudplow/cloudplow.py", line 64, in <module>
conf.load()
File "/opt/cloudplow/utils/config.py", line 256, in load
cfg, upgraded = self.upgrade_settings(json.load(fp))
File "/usr/lib/python3.8/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 22 column 3 (char 514)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

I'm a big fan of your container and I hope we can figure out a solution :)

**Comment by slyre1337** [comment]
fixed by generating new config file, sorry for annoying :D

**Comment by sabrsorensen** [comment]
No worries, glad you were able to fix it! Did you make any changes to your config file before you started seeing errors or did cloudplow upgrade the config automatically, introducing the invalid format?

**Comment by slyre1337** [comment]
I've actually had it happen multiple times over the past 1-2 years now of using cloudplow that an update made it so my config file was throwing errors. Every time I was able to fix it by deleting my config, letting it generate a new one and then insert my parameters into the new config file again.
This time it was throwing different errors from before though, so I thought it had to be something different but I guess not. 

I didn't change anything at all. I had the container setup and running about 2 months ago and never changed anything from then.
