### ISSUE TITLE
Init Script Has Hardcoded Config Directory

### ISSUE THREAD

**Issue by dcplaya** [sabrsorensen/alpine-cloudplow#5]
I run your docker container inside my k8s cluster with an init container that grabs my RClone config from a git repo. I specified a "random" directory (`/shared/Configs`) to store the config file in and updated the Cloudplow docker `ENV` to reflect the new location of the config files. When I did this, the init container writes the files as root while the Cloudplow container runs as UID `1000`. Since the Cloudplow init script only fixes perms on `/config` and not based on the `ENV` variable `CLOUDPLOW_CONFIG`, the init script fails to fix the perms.

For now, I simply set the perms in my own init container before handing it off to the Cloudplow container, but shouldn't the init script look at the ENV variable and set the perms based on that location? I could have also set the folder to be `/config` instead of `/shared` but that still doesn't address the underlying issue. 

Link to init script line that is the issue
https://github.com/sabrsorensen/alpine-cloudplow/blob/441c63debde6fa0d00def2a4e8beba1ba9f170f9/root/etc/cont-init.d/10-init_user_and_fix_permissions#L66

Also, in case its useful, here is a link to my k8s cloudplow deployment 
https://github.com/dcplaya/home-cluster/blob/main/cluster/media/sync/cloudplow-uploader.yaml

Not a show stopping bug but if the perms are not correct, RClone eventually fails (seems almost random, not always at the same spot) with an error about unable to write to the rclone config file. I assume it has something to do with a token update. RClone also currently doesn't allow immutable configs, hence why RW perms are required.

**Comment by sabrsorensen** [comment]
@dcplaya Thanks for the feedback and detailed info! Please try the `sabrsorensen/alpine-cloudplow:init_config` tag and see if that resolves the issue.

**Comment by dcplaya** [comment]
Gave it a go, see my comment [here](https://github.com/sabrsorensen/alpine-cloudplow/commit/3d767767c71e5653c2468997ac653a47a32b0239#r47626755)

**Comment by sabrsorensen** [comment]
Thanks for trying it out and your comment. I think you're right, a truly flexible solution would be parsing the environment variables and config files for the user-specified file locations, but I don't think it's unreasonable that a container rely on an expected configuration, especially if documented such as in the sample configuration in the README. Please feel free to fork and figure out a solution for your stack, I'd be happy to review a PR if you get something working!
